[versions]
kotlin = "2.3.0"
ksp = "2.3.4"
solon = "3.8.3"
jimmer = "0.9.120"
saToken = "1.44.0"
okhttp = "5.3.2"
jacksonKotlin = "2.19.2"
flyway = "11.20.1"
coroutines = "1.10.2"
hikari = "7.0.2"
sqlite = "3.51.1.0"
graalvmNativePlugin = "0.11.3"
webauthn4j = "0.28.5.RELEASE"
asm = "9.5"
benManesVersions = "0.53.0"

[libraries]
solon-parent = { module = "org.noear:solon-parent", version.ref = "solon" }
solon-web = { module = "org.noear:solon-web" }
solon-aot = { module = "org.noear:solon-aot" }
solon-logging-logback = { module = "org.noear:solon-logging-logback" }
solon-serialization-jackson = { module = "org.noear:solon-serialization-jackson" }
solon-scheduling-simple = { module = "org.noear:solon-scheduling-simple" }
solon-test = { module = "org.noear:solon-test" }

sa-token-solon = { module = "cn.dev33:sa-token-solon-plugin", version.ref = "saToken" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonKotlin" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

jimmer-client = { module = "org.babyfish.jimmer:jimmer-client", version.ref = "jimmer" }
jimmer-sql-kotlin = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }

hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

webauthn4j-core = { module = "com.webauthn4j:webauthn4j-core", version.ref = "webauthn4j" }

graalvm-native-plugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "graalvmNativePlugin" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

[plugins]
"kotlin-jvm" = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
"ksp" = { id = "com.google.devtools.ksp", version.ref = "ksp" }
benManesVersions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
